#!/usr/bin/env python3
"""make_register_manifest.py — write predictions/MANIFEST.sha256.

One SHA-256 per registered statement, frozen pipeline output and input data
file. Quoting the manifest's own SHA-256 in a public deposit description (for
example a Zenodo version) makes the deposit date an independent timestamp of
the exact register content. `--check` exits 1 if the manifest is stale.

Usage:
    python3 pipelines/make_register_manifest.py          # write the manifest
    python3 pipelines/make_register_manifest.py --check  # verify it is current
    python3 pipelines/make_register_manifest.py --digest # print the manifest's own SHA-256
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTER = REPO_ROOT / "predictions"
MANIFEST = REGISTER / "MANIFEST.sha256"
PATTERNS = ("*/prediction.md", "*/pipeline_output*.json", "*/observed_data.json")


def build() -> str:
    files = sorted({p for pat in PATTERNS for p in REGISTER.glob(pat)})
    lines = ["# SHA-256 of every registered statement, frozen output and input-data file.",
             "# Generated by pipelines/make_register_manifest.py. Do not edit by hand."]
    for f in files:
        lines.append(f"{hashlib.sha256(f.read_bytes()).hexdigest()}  {f.relative_to(REPO_ROOT).as_posix()}")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--digest", action="store_true")
    args = ap.parse_args(argv)
    text = build()
    if args.check:
        ok = MANIFEST.is_file() and MANIFEST.read_text(encoding="utf-8") == text
        print("manifest is current" if ok else "manifest is stale: run python3 pipelines/make_register_manifest.py")
        return 0 if ok else 1
    if args.digest:
        print(hashlib.sha256(MANIFEST.read_bytes()).hexdigest())
        return 0
    MANIFEST.write_text(text, encoding="utf-8")
    print(f"wrote {MANIFEST.relative_to(REPO_ROOT)} ({len(text.splitlines()) - 2} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
