#!/usr/bin/env python3
"""Generate LaTeX tables from best-fit CSV outputs (v11.0.0).

Inputs:
- <fit-dir>/bestfit_summary.csv  (written by late_time_make_figures.py)

Outputs:
- <fit-dir>/bestfit_summary.tex

This script is stdlib-only (no numpy), so it can run in minimal environments.
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Any, Dict, List, Optional

from _outdir import resolve_outdir


MODEL_LATEX = {
    "lcdm": r"$\Lambda$CDM",
    "gsc_powerlaw": r"GSC (power-law)",
    "gsc_transition": r"GSC (transition)",
}


def _f(x: Any) -> float:
    try:
        return float(x)
    except Exception:
        return float("nan")


def _fmt(x: Any, *, digits: int = 3) -> str:
    v = _f(x)
    if not math.isfinite(v):
        return "--"
    # Strip trailing zeros by using general format for small-ish digits.
    return f"{v:.{digits}g}"


def _fmt_fixed(x: Any, *, digits: int = 2) -> str:
    v = _f(x)
    if not math.isfinite(v):
        return "--"
    return f"{v:.{digits}f}"


def _read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        if r.fieldnames is None:
            raise ValueError(f"Missing CSV header: {path}")
        return [row for row in r if row]


def _model_order_key(m: str) -> int:
    order = ["lcdm", "gsc_transition", "gsc_powerlaw"]
    try:
        return order.index(m)
    except ValueError:
        return 999


def make_bestfit_summary_tex(rows: List[Dict[str, str]]) -> str:
    # Sort rows in a stable, paper-friendly order.
    rows = sorted(rows, key=lambda r: (_model_order_key(str(r.get("model", ""))), str(r.get("model", ""))))

    lines: List[str] = []
    lines.append("% Auto-generated by v11.0.0/scripts/late_time_make_tables.py")
    lines.append("% Requires: \\usepackage{booktabs}")
    lines.append("")
    lines.append("% Best-fit + model comparison")
    lines.append(r"\begin{tabular}{lrrrrrrrrrr}")
    lines.append(r"\toprule")
    lines.append(
        r"Model & $H_0$ & $\Omega_m$ & $p$ & $z_t$ & $r_d$ [Mpc] & $\chi^2$ & ndof & $\chi^2/\mathrm{ndof}$ & $\Delta\mathrm{AIC}$ & $\Delta\mathrm{BIC}$ \\"
    )
    lines.append(r"\midrule")

    for r in rows:
        model = str(r.get("model", "")).strip()
        mlabel = MODEL_LATEX.get(model, model.replace("_", r"\_"))
        H0 = _fmt_fixed(r.get("H0"), digits=2)
        Om = _fmt(r.get("Omega_m"), digits=4)
        p = _fmt(r.get("p"), digits=4)
        zt = _fmt(r.get("z_transition"), digits=4)
        rd = _fmt_fixed(r.get("rd_Mpc"), digits=1)
        chi2 = _fmt_fixed(r.get("chi2"), digits=2)
        ndof = str(r.get("ndof", "")).strip() or "--"
        c2nd = _fmt(r.get("chi2_over_ndof"), digits=4)
        dAIC = _fmt_fixed(r.get("delta_AIC_vs_lcdm"), digits=2)
        dBIC = _fmt_fixed(r.get("delta_BIC_vs_lcdm"), digits=2)

        lines.append(f"{mlabel} & {H0} & {Om} & {p} & {zt} & {rd} & {chi2} & {ndof} & {c2nd} & {dAIC} & {dBIC} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append("")

    # Optional breakdown table (useful for appendices / sanity checks).
    have_breakdown = any(("chi2_sn" in r or "chi2_bao" in r or "chi2_drift" in r or "chi2_cmb" in r) for r in rows)
    if have_breakdown:
        has_cmb = any(math.isfinite(_f(r.get("chi2_cmb"))) for r in rows)
        lines.append("% Chi^2 breakdown by dataset")
        if has_cmb:
            lines.append(r"\begin{tabular}{lrrrrrr}")
        else:
            lines.append(r"\begin{tabular}{lrrrrr}")
        lines.append(r"\toprule")
        if has_cmb:
            lines.append(
                r"Model & $\chi^2_{\mathrm{SN}}$ & $\chi^2_{\mathrm{BAO}}$ & $\chi^2_{\mathrm{drift}}$ & $\chi^2_{\mathrm{CMB}}$ & $\chi^2_{\mathrm{tot}}$ & ndof \\"
            )
        else:
            lines.append(r"Model & $\chi^2_{\mathrm{SN}}$ & $\chi^2_{\mathrm{BAO}}$ & $\chi^2_{\mathrm{drift}}$ & $\chi^2_{\mathrm{tot}}$ & ndof \\")
        lines.append(r"\midrule")
        for r in rows:
            model = str(r.get("model", "")).strip()
            mlabel = MODEL_LATEX.get(model, model.replace("_", r"\_"))
            c_sn = _fmt_fixed(r.get("chi2_sn"), digits=2)
            c_bao = _fmt_fixed(r.get("chi2_bao"), digits=2)
            c_drift = _fmt_fixed(r.get("chi2_drift"), digits=2)
            c_cmb = _fmt_fixed(r.get("chi2_cmb"), digits=2)
            c_tot = _fmt_fixed(r.get("chi2"), digits=2)
            ndof = str(r.get("ndof", "")).strip() or "--"
            if has_cmb:
                lines.append(f"{mlabel} & {c_sn} & {c_bao} & {c_drift} & {c_cmb} & {c_tot} & {ndof} \\\\")
            else:
                lines.append(f"{mlabel} & {c_sn} & {c_bao} & {c_drift} & {c_tot} & {ndof} \\\\")
        lines.append(r"\bottomrule")
        lines.append(r"\end{tabular}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fit-dir", type=Path, default=Path("v11.0.0/results/late_time_fit"))
    ap.add_argument(
        "--out-dir",
        "--outdir",
        dest="outdir",
        type=Path,
        default=None,
        help="Output root used when --out-tex is not set (CLI > GSC_OUTDIR > artifacts/release).",
    )
    ap.add_argument("--in-csv", type=Path, default=None)
    ap.add_argument("--out-tex", type=Path, default=None)
    args = ap.parse_args()

    fit_dir = args.fit_dir
    in_csv = args.in_csv or (fit_dir / "bestfit_summary.csv")
    if args.out_tex is not None:
        out_tex = Path(args.out_tex).expanduser().resolve()
    else:
        out_root = resolve_outdir(args.outdir, v101_dir=Path(__file__).resolve().parents[1])
        out_tex = (out_root / "late_time_tables" / "bestfit_summary.tex").resolve()
    print(f"[info] OUTDIR={out_tex.parent}")

    if not in_csv.exists():
        raise SystemExit(f"Missing expected input CSV: {in_csv}")

    rows = _read_csv(in_csv)
    if not rows:
        raise SystemExit(f"No rows loaded from: {in_csv}")

    tex = make_bestfit_summary_tex(rows)
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(tex, encoding="utf-8")
    print(f"WROTE {out_tex}")


if __name__ == "__main__":
    main()
