#!/usr/bin/env python3
"""Deterministically build Paper-2 assets from existing Phase-4 runners."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

SCHEMA = "phase4_paper2_assets_manifest_v1"
TOOL = "phase4_build_paper2_assets"
TOOL_VERSION = "m158-v2"
FAIL_MARKER = "PHASE4_BUILD_PAPER2_ASSETS_FAILED"
DEFAULT_CREATED_UTC_EPOCH = 946684800
ABS_TOKENS: Tuple[str, ...] = ("/Users/", "/home/", "/var/folders/", "C:\\Users\\")


class UsageError(Exception):
    """Invalid CLI usage."""


class BuildError(Exception):
    """Build failed."""


def _json_pretty(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=True) + "\n"


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _to_iso_utc(epoch_seconds: int) -> str:
    dt = datetime.fromtimestamp(int(epoch_seconds), tz=timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _resolve_path(base: Path, raw: str) -> Path:
    p = Path(str(raw)).expanduser()
    if p.is_absolute():
        return p.resolve()
    return (base / p).resolve()


def _sanitize(text: str, repo_root: Path) -> str:
    out = str(text)
    out = out.replace(str(repo_root.resolve()), repo_root.name)
    for token in ABS_TOKENS:
        out = out.replace(token, "<ABS>/")
    return out


def _load_json(path: Path) -> Dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise BuildError(f"failed to parse JSON: {path.name}") from exc
    if not isinstance(payload, dict):
        raise BuildError(f"JSON payload must be object: {path.name}")
    return payload


def _require_file(path: Path, label: str) -> Path:
    if not path.is_file():
        raise BuildError(f"missing {label}: {path}")
    return path


def _fmt_tex(x: Any) -> str:
    try:
        return f"{float(x):.6e}"
    except Exception:
        return "nan"


def _write_numbers_tex(path: Path, *, sn: Mapping[str, Any], joint: Mapping[str, Any]) -> None:
    sn_eps = sn.get("epsilon_em", {}) if isinstance(sn.get("epsilon_em"), Mapping) else {}
    joint_eps = joint.get("epsilon_em", {}) if isinstance(joint.get("epsilon_em"), Mapping) else {}
    joint_om = joint.get("omega_m", {}) if isinstance(joint.get("omega_m"), Mapping) else {}

    content = "\n".join(
        [
            "% Deterministic file generated by phase4_build_paper2_assets.py",
            f"\\newcommand{{\\epsilonSNMean}}{{{_fmt_tex(sn_eps.get('mean'))}}}",
            f"\\newcommand{{\\epsilonSNPsixteen}}{{{_fmt_tex(sn_eps.get('p16'))}}}",
            f"\\newcommand{{\\epsilonSNPeightyfour}}{{{_fmt_tex(sn_eps.get('p84'))}}}",
            f"\\newcommand{{\\epsilonJointMean}}{{{_fmt_tex(joint_eps.get('mean'))}}}",
            f"\\newcommand{{\\epsilonJointPsixteen}}{{{_fmt_tex(joint_eps.get('p16'))}}}",
            f"\\newcommand{{\\epsilonJointPeightyfour}}{{{_fmt_tex(joint_eps.get('p84'))}}}",
            f"\\newcommand{{\\omegaMJointMean}}{{{_fmt_tex(joint_om.get('mean'))}}}",
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")


def _copy(src: Path, dst: Path) -> Dict[str, Any]:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)
    return {
        "filename": dst.as_posix(),
        "sha256": _sha256_file(dst),
        "bytes": int(dst.stat().st_size),
    }


def _parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Build deterministic Paper-2 publication assets.")
    ap.add_argument("--repo-root", default="v11.0.0")
    ap.add_argument("--preset", choices=("ci_smoke", "paper_grade"), default="ci_smoke")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--workdir", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--pantheon-manifest", default=None)
    ap.add_argument("--desi-bao-manifest", default=None)
    ap.add_argument("--include-theory-annex", action="store_true")
    ap.add_argument("--created-utc", type=int, default=DEFAULT_CREATED_UTC_EPOCH)
    ap.add_argument("--format", choices=("json", "text"), default="text")
    return ap.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    try:
        args = _parse_args(argv)
        repo_root = Path(str(args.repo_root)).expanduser().resolve()
        if not repo_root.is_dir():
            raise UsageError(f"repo-root not found: {repo_root}")

        preset = str(args.preset)
        run_mode = "paper_grade" if preset == "paper_grade" else "demo"
        created_epoch = int(args.created_utc)
        created_utc = _to_iso_utc(created_epoch)

        pantheon_manifest = _resolve_path(repo_root, args.pantheon_manifest) if args.pantheon_manifest else None
        desi_manifest = _resolve_path(repo_root, args.desi_bao_manifest) if args.desi_bao_manifest else None
        if run_mode == "paper_grade":
            if pantheon_manifest is None or not pantheon_manifest.is_file():
                raise UsageError("--preset paper_grade requires --pantheon-manifest")
            if desi_manifest is None or not desi_manifest.is_file():
                raise UsageError("--preset paper_grade requires --desi-bao-manifest")

        workdir = Path(str(args.workdir)).expanduser().resolve()
        outdir = Path(str(args.outdir)).expanduser().resolve()
        workdir.mkdir(parents=True, exist_ok=True)
        outdir.mkdir(parents=True, exist_ok=True)
        figures_dir = outdir / "figures"
        figures_dir.mkdir(parents=True, exist_ok=True)

        subrun_out = workdir / "paper2_subrun"
        if subrun_out.exists():
            shutil.rmtree(subrun_out)
        subrun_out.mkdir(parents=True, exist_ok=True)

        runner = repo_root / "scripts" / "phase4_make_paper2_artifacts.py"
        _require_file(runner, "phase4_make_paper2_artifacts.py")

        cmd: List[str] = [
            sys.executable,
            str(runner),
            "--repo-root",
            str(repo_root),
            "--outdir",
            str(subrun_out),
            "--seed",
            str(int(args.seed)),
            "--run-mode",
            run_mode,
            "--created-utc",
            str(created_epoch),
            "--format",
            "json",
        ]
        if pantheon_manifest is not None:
            cmd.extend(["--pantheon-manifest", str(pantheon_manifest)])
        if desi_manifest is not None:
            cmd.extend(["--desi-bao-manifest", str(desi_manifest)])

        proc = subprocess.run(cmd, cwd=str(repo_root.parent), text=True, capture_output=True)
        if proc.returncode != 0:
            msg = _sanitize((proc.stdout or "") + "\n" + (proc.stderr or ""), repo_root)
            raise BuildError(f"subtool run failed (exit={proc.returncode}): {msg[-1400:]}")

        sn_summary_path = _require_file(subrun_out / "sn_epsilon_posterior_summary.json", "SN summary")
        bao_summary_path = _require_file(subrun_out / "bao_leg_summary.json", "BAO summary")
        joint_summary_path = _require_file(subrun_out / "sn_bao_joint_summary.json", "joint summary")

        sn_summary = _load_json(sn_summary_path)
        bao_summary = _load_json(bao_summary_path)
        joint_summary = _load_json(joint_summary_path)

        artifact_rows: List[Dict[str, Any]] = []

        # Copy summary JSONs.
        for src, name in (
            (sn_summary_path, "sn_epsilon_posterior_summary.json"),
            (bao_summary_path, "bao_leg_summary.json"),
            (joint_summary_path, "sn_bao_joint_summary.json"),
        ):
            dst = outdir / name
            artifact_rows.append(_copy(src, dst))

        # Deterministic figure names for paper source.
        figure_map = (
            (subrun_out / "_subruns" / "sn" / "epsilon_posterior_1d.png", "fig_sn_epsilon_posterior_1d.png"),
            (subrun_out / "_subruns" / "sn" / "omega_m_vs_epsilon.png", "fig_sn_omega_m_vs_epsilon.png"),
            (subrun_out / "_subruns" / "bao" / "omega_m_vs_epsilon.png", "fig_bao_rd_degeneracy.png"),
            (subrun_out / "_subruns" / "joint" / "epsilon_posterior_1d.png", "fig_triangle1_epsilon_posterior_1d.png"),
            (subrun_out / "_subruns" / "joint" / "omega_m_vs_epsilon.png", "fig_triangle1_omega_m_vs_epsilon.png"),
        )
        for src, name in figure_map:
            _require_file(src, f"figure {name}")
            artifact_rows.append(_copy(src, figures_dir / name))

        # numbers.tex for manuscript.
        numbers_path = outdir / "numbers.tex"
        _write_numbers_tex(numbers_path, sn=sn_summary, joint=joint_summary)
        artifact_rows.append(
            {
                "filename": numbers_path.as_posix(),
                "sha256": _sha256_file(numbers_path),
                "bytes": int(numbers_path.stat().st_size),
            }
        )

        if bool(args.include_theory_annex):
            bridge_tool = repo_root / "bridges" / "phase4_qcd_gravity_bridge_v0.1" / "tools" / "make_qcd_gravity_bridge_artifacts.py"
            _require_file(bridge_tool, "QCD-gravity bridge artifact generator")
            annex_out = workdir / "theory_annex_subrun"
            if annex_out.exists():
                shutil.rmtree(annex_out)
            annex_out.mkdir(parents=True, exist_ok=True)

            bridge_cmd: List[str] = [
                sys.executable,
                str(bridge_tool),
                "--outdir",
                str(annex_out),
                "--preset",
                "paper_grade" if preset == "paper_grade" else "ci_smoke",
                "--seed",
                str(int(args.seed)),
                "--created-utc",
                str(created_epoch),
                "--emit-plot",
                "1",
                "--format",
                "json",
            ]
            bridge_proc = subprocess.run(bridge_cmd, cwd=str(repo_root.parent), text=True, capture_output=True)
            if bridge_proc.returncode != 0:
                msg = _sanitize((bridge_proc.stdout or "") + "\n" + (bridge_proc.stderr or ""), repo_root)
                raise BuildError(f"theory annex run failed (exit={bridge_proc.returncode}): {msg[-1400:]}")

            annex_dst = outdir / "theory" / "qcd_gravity_bridge"
            annex_files: List[Path] = [
                _require_file(annex_out / "qcd_gravity_bridge_numbers.json", "QCD-gravity bridge JSON"),
                _require_file(annex_out / "qcd_gravity_bridge_kill_matrix.csv", "QCD-gravity bridge kill matrix CSV"),
            ]
            annex_plot = annex_out / "qcd_gravity_bridge_scale_plot.png"
            if annex_plot.is_file():
                annex_files.append(annex_plot)
            for src in annex_files:
                artifact_rows.append(_copy(src, annex_dst / src.name))

        # Use relative filenames in manifest.
        normalized_rows: List[Dict[str, Any]] = []
        for row in artifact_rows:
            rel = Path(str(row["filename"]))
            if rel.is_absolute():
                rel = rel.relative_to(outdir)
            normalized_rows.append({
                "filename": rel.as_posix(),
                "sha256": str(row["sha256"]),
                "bytes": int(row["bytes"]),
            })

        payload: Dict[str, Any] = {
            "schema": SCHEMA,
            "tool": TOOL,
            "tool_version": TOOL_VERSION,
            "created_utc": created_utc,
            "deterministic": True,
            "paths_redacted": True,
            "preset": preset,
            "seed": int(args.seed),
            "run_mode": run_mode,
            "theory_annex_included": bool(args.include_theory_annex),
            "inputs": {
                "pantheon_manifest_basename": pantheon_manifest.name if pantheon_manifest is not None else None,
                "pantheon_manifest_sha256": _sha256_file(pantheon_manifest) if pantheon_manifest is not None else None,
                "desi_bao_manifest_basename": desi_manifest.name if desi_manifest is not None else None,
                "desi_bao_manifest_sha256": _sha256_file(desi_manifest) if desi_manifest is not None else None,
            },
            "artifacts": sorted(normalized_rows, key=lambda x: str(x["filename"])),
        }

        manifest_text = _json_pretty(payload)
        if any(tok in manifest_text for tok in ABS_TOKENS):
            raise BuildError("manifest contains absolute path token")
        manifest_path = outdir / "paper2_assets_manifest.json"
        manifest_path.write_text(manifest_text, encoding="utf-8")

        if str(args.format) == "json":
            print(manifest_text, end="")
        else:
            print(f"schema={SCHEMA}")
            print(f"preset={preset}")
            print(f"run_mode={run_mode}")
            print(f"artifacts={len(payload['artifacts'])}")
            print(f"manifest={manifest_path.name}")
        return 0

    except (UsageError, BuildError) as exc:
        print(f"{FAIL_MARKER}: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
