"""Early-time bridge helpers for v11.0.0 (Option 2, E0 rd-only closure)."""

from .rd import (
    compute_rd_Mpc,
    omega_gamma_h2_from_Tcmb,
    omega_r_h2,
    z_drag_eisenstein_hu,
)
from .cmb_distance_priors import (
    compute_bridged_distance_priors,
    compute_full_history_distance_priors,
    compute_lcdm_distance_priors,
    z_star_hu_sugiyama,
)
from .cmb_shift_params import (
    compute_bridged_shift_params,
    compute_full_history_shift_params,
    compute_lcdm_shift_params,
)
from .cmb_priors_driver import (
    CMBPriorsDriverConfig,
    CMBPriorsEvaluation,
    default_cmb_key_aliases,
    evaluate_cmb_priors_dataset,
    materialize_cmb_prior_values,
    predict_cmb_observables,
)
from .params import (
    EarlyTimeParams,
    early_time_params_from_namespace,
    early_time_params_from_values,
)
from .numerics_invariants import (
    CHECK_ID_ALIAS_THETA_100,
    CHECK_ID_FINITE_POSITIVE_CORE,
    CHECK_ID_IDENTITY_LA,
    CHECK_ID_IDENTITY_RD_UNITS,
    CORE_POSITIVE_REQUIRED_KEYS,
    DEFAULT_REQUIRED_CHECK_IDS,
    DEFAULT_POSITIVE_KEYS,
    INVARIANTS_SCHEMA_VERSION,
    check_alias_consistency,
    check_finite_positive,
    check_identity_relations,
    run_early_time_invariants,
)
from .cmb_microphysics_knobs import (
    KNOB_SPECS,
    KnobSpec,
    MicrophysicsKnobs,
    assess_knobs as assess_microphysics_knobs,
    knobs_from_dict as microphysics_knobs_from_dict,
    knobs_to_dict as microphysics_knobs_to_dict,
    validate_knobs as validate_microphysics_knobs,
)
from .e2_deformations import (
    A_BUMP_MAX,
    A_BUMP_MIN,
    A_DIP_MAX,
    A_DIP_MIN,
    DEFAULT_BUMP_Z_HI,
    DEFAULT_BUMP_Z_LO,
    DEFAULT_DIP_Z_HI,
    DEFAULT_DIP_Z_LO,
    DEFAULT_FACTOR_FLOOR,
    DEFAULT_WINDOW_W,
    DipBumpWindowDeformation,
    window as dip_bump_window,
)

__all__ = [
    "compute_rd_Mpc",
    "omega_gamma_h2_from_Tcmb",
    "omega_r_h2",
    "z_drag_eisenstein_hu",
    "compute_bridged_distance_priors",
    "compute_full_history_distance_priors",
    "compute_lcdm_distance_priors",
    "compute_bridged_shift_params",
    "compute_full_history_shift_params",
    "compute_lcdm_shift_params",
    "CMBPriorsDriverConfig",
    "CMBPriorsEvaluation",
    "default_cmb_key_aliases",
    "evaluate_cmb_priors_dataset",
    "materialize_cmb_prior_values",
    "predict_cmb_observables",
    "z_star_hu_sugiyama",
    "EarlyTimeParams",
    "early_time_params_from_namespace",
    "early_time_params_from_values",
    "INVARIANTS_SCHEMA_VERSION",
    "CHECK_ID_FINITE_POSITIVE_CORE",
    "CHECK_ID_ALIAS_THETA_100",
    "CHECK_ID_IDENTITY_LA",
    "CHECK_ID_IDENTITY_RD_UNITS",
    "CORE_POSITIVE_REQUIRED_KEYS",
    "DEFAULT_REQUIRED_CHECK_IDS",
    "DEFAULT_POSITIVE_KEYS",
    "check_alias_consistency",
    "check_finite_positive",
    "check_identity_relations",
    "run_early_time_invariants",
    "KnobSpec",
    "KNOB_SPECS",
    "MicrophysicsKnobs",
    "assess_microphysics_knobs",
    "microphysics_knobs_from_dict",
    "microphysics_knobs_to_dict",
    "validate_microphysics_knobs",
    "A_BUMP_MAX",
    "A_BUMP_MIN",
    "A_DIP_MAX",
    "A_DIP_MIN",
    "DEFAULT_BUMP_Z_HI",
    "DEFAULT_BUMP_Z_LO",
    "DEFAULT_DIP_Z_HI",
    "DEFAULT_DIP_Z_LO",
    "DEFAULT_FACTOR_FLOOR",
    "DEFAULT_WINDOW_W",
    "DipBumpWindowDeformation",
    "dip_bump_window",
]
